from alembic import command
from alembic.config import Config
from alembic.util.exc import AutogenerateDiffsDetected
from sqlalchemy import func, select
from sqlalchemy.orm import Session

from app.db.session import make_engine
from app.models import Admin, Bill, Customer, Plan
from app.seed import seed_admin, seed_demo, seed_plans


def test_migrations_match_models(tmp_path, monkeypatch):
    from app.core.config import get_settings

    monkeypatch.setenv("DATABASE_URL", f"sqlite:///{tmp_path / 'm.db'}")
    get_settings.cache_clear()
    try:
        cfg = Config("alembic.ini")
        command.upgrade(cfg, "head")
        try:
            command.check(cfg)
        except AutogenerateDiffsDetected as exc:  # pragma: no cover
            raise AssertionError(f"Models changed without a migration: {exc}") from exc
        command.downgrade(cfg, "base")
    finally:
        get_settings.cache_clear()


def test_seed_is_idempotent(tmp_path):
    from app.db.base import Base

    engine = make_engine(f"sqlite:///{tmp_path / 's.db'}")
    Base.metadata.create_all(engine)
    with Session(engine) as db:
        assert seed_plans(db) == 27
        assert seed_admin(db) == "admin"
        assert seed_demo(db) == 5
        assert (seed_plans(db), seed_admin(db), seed_demo(db)) == (0, None, 0)
        assert db.scalar(select(func.count(Plan.id))) == 27
        assert db.scalar(select(func.count(Admin.id))) == 1
        assert db.scalar(select(func.count(Customer.id))) == 5
        assert db.scalar(select(func.count(Bill.id))) >= 5
