"""initial schema

Revision ID: 6955a2fe5322
Revises:
Create Date: 2026-10-06 03:15:57.941609

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6955a2fe5322"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "admins",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(length=50), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("username"),
    )
    op.create_table(
        "customers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("mobile_no", sa.String(length=10), nullable=False),
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column("dob", sa.Date(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("occupation", sa.String(length=80), nullable=False),
        sa.Column("aadhaar_last4", sa.String(length=4), nullable=False),
        sa.Column("house_no", sa.String(length=20), nullable=False),
        sa.Column("street", sa.String(length=80), nullable=False),
        sa.Column("city", sa.String(length=60), nullable=False),
        sa.Column("state", sa.String(length=60), nullable=False),
        sa.Column("pincode", sa.String(length=6), nullable=False),
        sa.Column(
            "connection_type",
            sa.Enum(
                "prepaid",
                "postpaid",
                "broadband",
                name="plan_category",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("customers", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_customers_email"), ["email"], unique=True)
        batch_op.create_index(batch_op.f("ix_customers_mobile_no"), ["mobile_no"], unique=True)

    op.create_table(
        "plans",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "category",
            sa.Enum(
                "prepaid",
                "postpaid",
                "broadband",
                name="plan_category",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("name", sa.String(length=60), nullable=False),
        sa.Column("price", sa.Integer(), nullable=False),
        sa.Column("validity_days", sa.Integer(), nullable=False),
        sa.Column("data", sa.String(length=40), nullable=False),
        sa.Column("calls", sa.String(length=40), nullable=True),
        sa.Column("sms", sa.String(length=40), nullable=True),
        sa.Column("speed", sa.String(length=20), nullable=True),
        sa.Column("post_fup_speed", sa.String(length=20), nullable=True),
        sa.Column("is_popular", sa.Boolean(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("plans", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_plans_category"), ["category"], unique=False)

    op.create_table(
        "feedback",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("customer_id", sa.Integer(), nullable=True),
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column(
            "satisfaction",
            sa.Enum(
                "excellent",
                "good",
                "average",
                "bad",
                name="satisfaction",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("comments", sa.Text(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.ForeignKeyConstraint(["customer_id"], ["customers.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "notifications",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("customer_id", sa.Integer(), nullable=True),
        sa.Column("channel", sa.String(length=10), nullable=False),
        sa.Column("recipient", sa.String(length=255), nullable=False),
        sa.Column("subject", sa.String(length=200), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("delivered", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.ForeignKeyConstraint(["customer_id"], ["customers.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("notifications", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_notifications_customer_id"), ["customer_id"], unique=False
        )

    op.create_table(
        "payments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("reference", sa.String(length=24), nullable=False),
        sa.Column("customer_id", sa.Integer(), nullable=False),
        sa.Column("amount", sa.Integer(), nullable=False),
        sa.Column("card_brand", sa.String(length=20), nullable=False),
        sa.Column("card_last4", sa.String(length=4), nullable=False),
        sa.Column("cardholder_name", sa.String(length=80), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.ForeignKeyConstraint(["customer_id"], ["customers.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("reference"),
    )
    op.create_table(
        "tickets",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("ticket_no", sa.String(length=12), nullable=False),
        sa.Column("customer_id", sa.Integer(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("assigned_to", sa.String(length=50), nullable=False),
        sa.Column(
            "status",
            sa.Enum("open", "resolved", name="ticket_status", native_enum=False, length=20),
            nullable=False,
        ),
        sa.Column("response", sa.Text(), nullable=True),
        sa.Column("responded_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.ForeignKeyConstraint(["customer_id"], ["customers.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("ticket_no"),
    )
    with op.batch_alter_table("tickets", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_tickets_customer_id"), ["customer_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_tickets_status"), ["status"], unique=False)

    op.create_table(
        "bills",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("invoice_no", sa.String(length=24), nullable=False),
        sa.Column("customer_id", sa.Integer(), nullable=False),
        sa.Column("plan_id", sa.Integer(), nullable=True),
        sa.Column("payment_id", sa.Integer(), nullable=True),
        sa.Column(
            "category",
            sa.Enum(
                "prepaid",
                "postpaid",
                "broadband",
                name="plan_category",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("plan_name", sa.String(length=60), nullable=False),
        sa.Column("benefits", sa.String(length=255), nullable=False),
        sa.Column("amount", sa.Integer(), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.ForeignKeyConstraint(["customer_id"], ["customers.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["payment_id"], ["payments.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["plan_id"], ["plans.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("invoice_no"),
    )
    with op.batch_alter_table("bills", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_bills_category"), ["category"], unique=False)
        batch_op.create_index(batch_op.f("ix_bills_customer_id"), ["customer_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_bills_start_date"), ["start_date"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema.

    Dropping a table also drops its indexes. Dropping the indexes first fails on MySQL,
    which won't drop an index a foreign key still relies on, so drop tables child-first.
    """
    for table in (
        "notifications",
        "feedback",
        "tickets",
        "bills",
        "payments",
        "plans",
        "admins",
        "customers",
    ):
        op.drop_table(table)
